name: bandit
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install bandit
      - name: Run Bandit Report
        run: bandit -r /home/amine/epsi/Integration Scripting/Seance2/PROJET/django-aloe-bdd
